name: pp_28
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  uuid: ^4.0.10
  masked_text: ^1.0.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.0
  hive: 2.2.3
  hive_flutter: ^1.1.0
  carousel_slider: ^4.2.1
  flutter_svg: 2.0.9
  google_fonts: ^6.1.0
  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  in_app_review: ^2.0.8
  flutter_markdown: ^0.6.20
  webview_flutter_wkwebview: ^3.12.0
  webview_flutter_android: ^3.15.0
  webview_flutter: ^4.7.0
  firebase_core: ^2.25.5
  firebase_crashlytics: ^3.4.16
  firebase_remote_config: ^4.3.15
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icon_rounded.png

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/