name: pp_28
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-132.0.dev <4.0.0'

dependencies:
  intl: ^0.19.0
  uuid: ^4.0.10
  masked_text: ^1.0.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.0
  hive: 2.2.3
  hive_flutter: ^1.1.0
  carousel_slider: ^4.2.1
  flutter_svg: 2.0.9
  google_fonts: ^6.1.0
  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  in_app_review: ^2.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.7

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/